# https://docs.docker.com/compose/environment-variables/#the-env-file
# https://github.com/NuGet/Home/issues/10491#issuecomment-778841003
version: '3'
services:
  gateway:
    build:
      context: ../../
      dockerfile: src/ApiGateway/Dockerfile
    container_name: ecommerce-gateway
    restart: on-failure
    ports:
      - ${GATEWAY_PORT}:80
    networks:
      - ecommerce

  catalogs:
    image: catalogs:${TAG}
    build:
      args:
        Version: "1"
      context: ../../
      dockerfile: src/Services/Catalogs/Dockerfile
    container_name: ecommerce-catalogs
    restart: on-failure
    ports:
      - ${CATALOGS_SVC_PORT}:80
    depends_on:
      - postgres
      - rabbitmq
      - mongo
    networks:
      - ecommerce

  identity:
    image: identity:${TAG}
    build:
      args:
        Version: "1"
      context: ../../
      dockerfile: src/Services/Identity/Dockerfile
    container_name: ecommerce-identity
    restart: on-failure
    ports:
      - ${IDENTITY_SVC_PORT}:80
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - ecommerce

  customers:
    image: customers:${TAG}
    build:
      args:
        Version: "1"
      context: ../../
      dockerfile: src/Services/Customers/Dockerfile
    container_name: ecommerce-customers
    restart: on-failure
    ports:
      - ${CUSTOMERS_SVC_PORT}:80
    depends_on:
      - postgres
      - rabbitmq
      - mongo
    networks:
      - ecommerce

    #######################################################
    #  rabbitmq
    #######################################################
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: on-failure
    ports:
      - 5672:5672
      - 15672:15672
      # volumes:
      #   - rabbitmq:/var/lib/rabbitmq
    networks:
      - ecommerce

    #######################################################
    #  mongo
    #######################################################
  mongo:
    image: mongo
    container_name: mongo
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - ecommerce

    #######################################################
    #  postgres
    #######################################################
  postgres:
    image: postgres:11.1-alpine
    container_name: postgres
    ports:
      - '5432:5432'
    restart: on-failure
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - ecommerce

  #######################################################
  #  eventstore-db
  #######################################################
  eventstore:
    image: eventstore/eventstore:latest
    container_name: eventstore
    restart: on-failure
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=false
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_MEM_DB=true
    ports:
      - "1113:1113"
      - "2113:2113"
    networks:
      - ecommerce

networks:
  ecommerce:
    name: ecommerce
    driver: bridge