version: '3'
services:
  catalogs:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoOptions__ConnectionString=mongodb://mongo:${MONGO_PORT}
      - DatabaseName=ECommerce-services-catalogs
      - PostgresOptions__ConnectionString=Server=postgres;Port=5432;Database=ECommerce.Services.Catalogs;User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Include Error Detail=true
      - PostgresOptions__UseInMemory=false
      - RabbitConfiguration__Hostname=rabbitmq
      - RabbitConfiguration__UserName=guest
      - RabbitConfiguration__Password=guest
      - RabbitConfiguration__Port=5672
      - OutboxOptions__ConnectionString=Server=postgres;Port=5432;Database=ECommerce.Services.Catalogs;User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Include Error Detail=true
      - HangfireMessageSchedulerOptions__ConnectionString=Server=postgres;Port=5432;Database=ECommerce.Services.Catalogs;User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Include Error Detail=true
      - InternalMessageSchedulerOptions__ConnectionString=Server=postgres;Port=5432;Database=ECommerce.Services.Catalogs;User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Include Error Detail=true
  rabbitmq:
    ports:
      - 15672:15672
      - 5672:5672

  postgres:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  mongo:
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
