# https://docs.docker.com/compose/environment-variables/#the-env-file
# https://github.com/NuGet/Home/issues/10491#issuecomment-778841003
version: "3.8"

services:
  gateway:
    build:
      context: ../../
      dockerfile: src/ApiGateway/Dockerfile
    container_name: ecommerce-gateway
    restart: on-failure
    ports:
      - ${GATEWAY_PORT}:80
    networks:
      - ecommerce

  catalogs:
    image: catalogs:${TAG}
    build:
      args:
        Version: "1"
      context: ../../
      dockerfile: src/Services/Catalogs/Dockerfile
    container_name: ecommerce-catalogs
    restart: on-failure
    ports:
      - ${CATALOGS_SVC_PORT}:80
    depends_on:
      - postgres
      - rabbitmq
      - mongo
    networks:
      - ecommerce

  identity:
    image: identity:${TAG}
    build:
      args:
        Version: "1"
      context: ../../
      dockerfile: src/Services/Identity/Dockerfile
    container_name: ecommerce-identity
    restart: on-failure
    ports:
      - ${IDENTITY_SVC_PORT}:80
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - ecommerce

  customers:
    image: customers:${TAG}
    build:
      args:
        Version: "1"
      context: ../../
      dockerfile: src/Services/Customers/Dockerfile
    container_name: ecommerce-customers
    restart: on-failure
    ports:
      - ${CUSTOMERS_SVC_PORT}:80
    depends_on:
      - postgres
      - rabbitmq
      - mongo
    networks:
      - ecommerce

      #######################################################
    #  rabbitmq
    #######################################################
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: on-failure
    ports:
      - 5672:5672
      - 15672:15672
      # volumes:
      #   - rabbitmq:/var/lib/rabbitmq
    networks:
      - ecommerce

    #######################################################
    #  mongo
    #######################################################
  mongo:
    image: mongo
    container_name: mongo
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - ecommerce

    #######################################################
    #  postgres
    #######################################################
  postgres:
    image: postgres:11.1-alpine
    container_name: postgres
    restart: on-failure
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - ecommerce

  #######################################################
  #  eventstore-db
  #######################################################
  eventstore:
    image: eventstore/eventstore:latest
    container_name: eventstore
    restart: on-failure
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=false
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_MEM_DB=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore
    networks:
      - ecommerce

#   #######################################################
#   #  Redis
#   #######################################################

  # redis:
  #   image: redis
  #   container_name: redis
  #   restart: unless-stopped
  #   networks:
  #     - ecommerce
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - redis:/data


   #######################################################
   #  Portainer
   #######################################################
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000
    networks:
      - ecommerce

   #######################################################
   #  elasticsearch
   #######################################################
  elasticsearch:
    container_name: elastic_search
    restart: on-failure
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - ecommerce

   #######################################################
   #  kibana
   #######################################################
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.3
    container_name: kibana
    restart: on-failure
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic_search:9200
    ports:
      - "5601:5601"
    networks:
      - ecommerce
    depends_on:
      - elasticsearch

  jaeger:
    container_name: jaeger
    restart: on-failure
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
    networks:
      - ecommerce

   #######################################################
   #  zipkin
   #######################################################
  zipkin:
    image: openzipkin/zipkin:latest
    restart: on-failure
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - ecommerce

   #######################################################
   #  otel-collector
   #######################################################
  otel-collector:
    image: otel/opentelemetry-collector-contrib-dev:latest
    command: ["--config=/etc/otel-collector-config.yaml", ""]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger
      - zipkin
    networks:
      - ecommerce

   #######################################################
   # prometheus
   #######################################################
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: on-failure
    user: root
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - ecommerce

   #######################################################
   # node_exporter
   #######################################################
  node_exporter:
    container_name: node_exporter
    restart: on-failure
    image: prom/node-exporter
    ports:
      - '9101:9100'
    networks:
      - ecommerce

   #######################################################
   # grafana
   #######################################################
  grafana:
    container_name: grafana
    restart: on-failure
    image: grafana/grafana
    ports:
      - '3000:3000'
    networks:
      - ecommerce

networks:
  ecommerce:
    name: ecommerce

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
  elastic-data:
