version: '3.7'
services:
  gateway:
    build:
      context: ../../
      dockerfile: src/ApiGateway/Dockerfile
    container_name: ecommerce-gateway
    # restart: unless-stopped
    ports:
      - ${GATEWAY_PORT}:80
    networks:
      - ecommerce

  catalogs:
    image: catalogs:${TAG}
    build:
      args:
        Version: "1"
      context: ../../
      dockerfile: src/Services/Catalogs/Dockerfile
    container_name: ecommerce-catalogs
    # restart: unless-stopped
    ports:
      - ${CATALOGS_SVC_PORT}:80
    env_file:
      - ../../.docker-envs/catalogs.env
    networks:
      - ecommerce

  identity:
    image: identity:${TAG}
    build:
      args:
        Version: "1"
      context: ../../
      dockerfile: src/Services/Identity/Dockerfile
    container_name: ecommerce-identity
    # restart: unless-stopped
    ports:
      - ${IDENTITY_SVC_PORT}:80
    networks:
      - ecommerce

  customers:
    image: customers:${TAG}
    build:
      args:
        Version: "1"
      context: ../../
      dockerfile: src/Services/Customers/Dockerfile
    container_name: ecommerce-customers
    # restart: unless-stopped
    ports:
      - ${CUSTOMERS_SVC_PORT}:80
    networks:
      - ecommerce

# https://docs.docker.com/compose/networking/
# https://stackoverflow.com/questions/38088279/communication-between-multiple-docker-compose-projects
networks:
  ecommerce:
    name: ecommerce-network
    external: true