version: '3'

networks:
  ecommerce:
    name: ecommerce
    driver: bridge

volumes:
    eventecommerce-volume-data:
    eventecommerce-volume-logs:

services:
    #######################################################
    #  rabbitmq
    #######################################################
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: on-failure
    ports:
      - 5672:5672
      - 15672:15672
      # volumes:
      #   - rabbitmq:/var/lib/rabbitmq
    networks:
      - ecommerce

    #######################################################
    #  mongo
    #######################################################
  mongo:
    image: mongo
    container_name: mongo
    restart: on-failure
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=secret
    ports: 
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - ecommerce

    #######################################################
    #  postgres
    #######################################################
  postgres:
    image: postgres:11.1-alpine
    container_name: postgres
    restart: on-failure
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - ecommerce

#   #######################################################
#   #  Redis
#   #######################################################

  # redis:
  #   image: redis
  #   container_name: redis
  #   restart: unless-stopped
  #   networks:
  #     - ecommerce
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - redis:/data

