name: Test-Report

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Publish test results
      uses: phoenix-actions/test-reporting@v10
      id: test-report
      with:
          name: Tests Results
          artifact: test-results
          reporter: dotnet-trx
          path: '**/test-results.trx'
          output-to: 'checks'
          fail-on-error: 'false'